apiVersion: v1
kind: Service
metadata:
  name: dify-sandbox
  namespace: dify
spec:
  selector:
    app: dify-sandbox
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8194
      targetPort: 8194
