apiVersion: v1
kind: Service
metadata:
  name: dify-weaviate
  namespace: dify
spec:
  selector:
    app: dify-weaviate
  type: ClusterIP
  ports:
    - name: weaviate
      protocol: TCP
      port: 8080
      targetPort: weaviate
