apiVersion: v1
kind: Service
metadata:
  name: ssrf-proxy
  namespace: dify
spec:
  selector:
    app: ssrf-proxy
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
  type: ClusterIP
