kind: Service
apiVersion: v1
metadata:
  name: dify-nginx
  namespace: dify
spec:
  selector:
    app: dify-nginx
  type: LoadBalancer
  ports:
    - name: nginx
      port: 8008
      targetPort: 8008
