apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-api
  namespace: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-api
  template:
    metadata:
      labels:
        app: dify-api
    spec:
      restartPolicy: Always
      containers:
        - name: dify-api
          image: langgenius/dify-api:0.6.15
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          env:
            - name: MODE
              value: api
            - name: LOG_LEVEL
              value: INFO
            - name: DEBUG
              value: "false"
            - name: FLASK_DEBUG
              value: "false"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: SECRET_KEY
            - name: CONSOLE_WEB_URL
              value: "http://dify-web.dify.svc.cluster.local:3000"
            - name: CONSOLE_API_URL
              value: "http://dify-worker.dify.svc.cluster.local:5001"
            - name: SERVICE_API_URL
              value: "http://dify-worker.dify.svc.cluster.local:5001"
            - name: APP_WEB_URL
              value: "http://dify-web.dify.svc.cluster.local:3000"
            - name: CHECK_UPDATE_URL
              value: "https://updates.dify.ai"
            - name: OPENAI_API_BASE
              value: "https://api.openai.com/v1"
            - name: FILES_ACCESS_TIMEOUT
              value: "300"
            - name: APP_MAX_ACTIVE_REQUESTS
              value: "0"
            - name: MIGRATION_ENABLED
              value: "true"
            - name: DEPLOY_ENV
              value: "PRODUCTION"
            - name: DIFY_BIND_ADDRESS
              value: "0.0.0.0"
            - name: DIFY_PORT
              value: "5001"
            - name: GUNICORN_TIMEOUT
              value: "360"
            - name: API_TOOL_DEFAULT_CONNECT_TIMEOUT
              value: "10"
            - name: API_TOOL_DEFAULT_READ_TIMEOUT
              value: "60"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: DB_DATABASE
            - name: SQLALCHEMY_POOL_SIZE
              value: "30"
            - name: SQLALCHEMY_POOL_RECYCLE
              value: "3600"
            - name: SQLALCHEMY_ECHO
              value: "false"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: REDIS_PORT
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: REDIS_USERNAME
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: REDIS_PASSWORD
            - name: REDIS_USE_SSL
              value: "false"
            - name: REDIS_DB
              value: "0"
            - name: CELERY_BROKER_URL
              value: >-
                redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1
            - name: BROKER_USE_SSL
              value: "false"
            - name: WEB_API_CORS_ALLOW_ORIGINS
              value: "*"
            - name: CONSOLE_CORS_ALLOW_ORIGINS
              value: "*"
            - name: STORAGE_TYPE
              value: local
            - name: STORAGE_LOCAL_PATH
              value: storage
            - name: VECTOR_STORE
              value: weaviate
            - name: WEAVIATE_ENDPOINT
              value: "http://weaviate.dify.svc.cluster.local:8080"
            - name: WEAVIATE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-api
                  key: WEAVIATE_API_KEY
            - name: UPLOAD_FILE_SIZE_LIMIT
              value: "15"
            - name: UPLOAD_FILE_BATCH_LIMIT
              value: "5"
            - name: ETL_TYPE
              value: dify
            - name: MULTIMODAL_SEND_IMAGE_FORMAT
              value: base64
            - name: UPLOAD_IMAGE_FILE_SIZE_LIMIT
              value: "10"
            - name: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
              value: "1000"
            - name: INVITE_EXPIRY_HOURS
              value: "72"
            - name: RESET_PASSWORD_TOKEN_EXPIRY_HOURS
              value: "24"
            - name: CODE_EXECUTION_ENDPOINT
              value: "http://sandbox.dify.svc.cluster.local:8194"
            - name: CODE_EXECUTION_API_KEY
              value: dify-sandbox
            - name: CODE_MAX_NUMBER
              value: "9223372036854775807"
            - name: CODE_MIN_NUMBER
              value: "-9223372036854775808"
            - name: CODE_MAX_STRING_LENGTH
              value: "80000"
            - name: TEMPLATE_TRANSFORM_MAX_LENGTH
              value: "80000"
            - name: CODE_MAX_STRING_ARRAY_LENGTH
              value: "30"
            - name: CODE_MAX_OBJECT_ARRAY_LENGTH
              value: "30"
            - name: CODE_MAX_NUMBER_ARRAY_LENGTH
              value: "1000"
            - name: SSRF_PROXY_HTTP_URL
              value: "http://ssrf-proxy.dify.svc.cluster.local:3128"
            - name: SSRF_PROXY_HTTPS_URL
              value: "http://ssrf-proxy.dify.svc.cluster.local:3128"
