apiVersion: v1
kind: Secret
metadata:
  name: dify-api
  namespace: dify
type: Opaque
data:
  SECRET_KEY: c2stOWY3M3MzbGpUWFZjTVQzQmxiM2xqVHF0c0tpR0hYVmNNVDNCbGJrRkpMSzdV
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: ZGlmeWFpMTIzNDU2
  DB_HOST: cG9zdGdyZXMuZGlmeS5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_PORT: NTQzMg==
  DB_DATABASE: ZGlmeS1kYg==
  REDIS_HOST: cmVkaXMuZGlmeS5zdmMuY2x1c3Rlci5sb2NhbA==
  REDIS_PORT: NjM3OQ==
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ZGlmeWFpMTIzNDU2
  CELERY_BROKER_URL: cmVkaXM6Ly9kZXZlbG9wZXI6ZGlmeWFpMTIzNDU2QHJlZGlzLmRpZnkuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OS8x
  WEAVIATE_API_KEY: V1ZGNVlUaGFIbGtZd2hHVVNtQ1Jnc1gzdEQ1bmdkTjhwa2lo
