apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: dify
spec:
  selector:
    app: dify-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
